export ANTIGEN_CACHE=false

source $HOME/.zshtools/lib/antigen/antigen.zsh

# For things that are very specific to the current machine. Like docker IP
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

# Load various lib files
antigen use oh-my-zsh

#
# Antigen Bundles
#
antigen bundle git
antigen bundle git-extras
antigen bundle ssh-agent

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen bundle devinsba/dotfiles
local os_antigen="$ANTIGEN_BUNDLES/devinsba/dotfiles/antigen.`uname`.zsh"
[ -f $os_antigen ] && source $os_antigen

antigen bundle ssh://git@bitbucket.org/devinsba/dotfiles-secret

if (($+WORK_REPO)) ; then
  antigen bundle $WORK_REPO
fi

#
# Antigen Theme
#
antigen theme devinsba/zsh-theme

antigen apply
